name:        leveldir
version:     "0.1.0"
github:      kazukisuzuki/leveldir
license:     PublicDomain
author:      kazuki
maintainer:  26251926+kazukisuzuki@users.noreply.github.com
description: Please see the README on GitHub at <https://github.com/kazukisuzuki/leveldir#readme>

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- filepath
- directory
- uuid

default-extensions:
- LambdaCase

library:
  source-dirs: src

executables:
  leveldir-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - leveldir

tests:
  leveldir-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - leveldir
